import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useRouter } from "next/router";
import { ConnectButton } from "@rainbow-me/rainbowkit";

export default function Home() {
  const router = useRouter();

  return (
    <div className={styles.container}>
      <Head>
        <title>Eat Money</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen w-full flex flex-col justify-center items-center">
        <div className="flex flex-row justify-center items-center">
          <button
            className="w-[10rem] h-12 bg-bg1"
            onClick={() => {
              router.push("/MarketPlace");
            }}
          >
            Enter Dapp
          </button>
          <ConnectButton showBalance={true}></ConnectButton>
          <button
            className="w-[10rem] h-12 bg-bg1"
            onClick={() => {
              router.push("/Restaurant");
            }}
          >
            Enter Restaurant
          </button>
        </div>
      </div>
    </div>
  );
}
